require("settings")
require("plugins")
require('keymaps')
require("telescope/settings")
require("plugin_config/neovimtree")
require("plugin_config/tagbar")
require("plugin_config/commenter")
require("plugin_config/ale_settings")
require("plugin_config/lsp")
require("plugin_config/git")
require('plugin_config/webdevicons')
require('plugin_config/surround_text')
require('plugin_config/terminal')
-- require('plugin_config/statusline')

vim.cmd [[ colorscheme gruvbox ]]
