require("settings")
require("plugins")
require('keymaps')
require("plugin_config/telescope")
require("plugin_config/neovimtree")
require("plugin_config/commenter")
require("plugin_config/lsp")
require('plugin_config/_mason')
require('plugin_config/_lsp_signature')
require('plugin_config/lsp_servers')
require('plugin_config/cmp')
require("plugin_config/git")
require('plugin_config/webdevicons')
require('plugin_config/surround_text')
require('plugin_config/terminal')
require('plugin_config/python_docstring')
require('plugin_config/multicursor')
require('plugin_config/gitsigns')
require('plugin_config/snippets')
require('plugin_config/harpoon')

vim.cmd [[ colorscheme gruvbox ]]
